### ISSUE TITLE
Does Window10 not support NVMe1.4b?

### ISSUE THREAD

**Issue by pomfei** [ken-yossy/nvmetool-win#11]
Does the Windows 10 suppotr the new feature Endurance Group Information (Log Identifier 09h) of NVMe spec 1.4  chapter 5.14.1.9 ? 
Follow this page (https://docs.microsoft.com/en-us/windows/win32/fileio/working-with-nvme-devices#example-nvme-get-log-pages-query) , i set ProtocolDataRequestValue to 0x09 and set ProtocolDataRequestSubValue3(CDW11) to 0x010000, but the SSD can not get the CDW11,it's always 0.
But in Linux using NVMe-cli i can get the righe data
So do you know how to add the Endurance Group Information (Log Identifier 09h) to the code?

**Comment by ken-yossy** [comment]
Hi @pomfei,

Thank you for your comments.

> Follow this page (https://docs.microsoft.com/en-us/windows/win32/fileio/working-with-nvme-devices#example-nvme-get-log-pages-query) , i set ProtocolDataRequestValue to 0x09 and set ProtocolDataRequestSubValue3(CDW11) to 0x010000, but the SSD can not get the CDW11,it's always 0.
> But in Linux using NVMe-cli i can get the righe data
> So do you know how to add the Endurance Group Information (Log Identifier 09h) to the code?

Ok, I will try some ways after reproducing your problem.
As reading your explanation, I'm afraid that we should use "ProtocolDataRequestSubValue" instead of "ProtocolDataRequestSubValue3" to pass any value as CDW11.

Regards,
Ken

**Comment by pomfei** [comment]
Hi @ken-yossy,

Great thanks for your help.

> As reading your explanation, I'm afraid that we should use "ProtocolDataRequestSubValue" instead of "ProtocolDataRequestSubValue3" to pass any value as CDW11.

I tried it and included ProtocolDataRequestSubValue2&3, but CDW11 is still 0

Regards,
Pomfei

**Comment by ken-yossy** [comment]
Hi @pomfei,

Thank you for your further information.
I have succeeded in sending ID via CDW11 on getting Endurance Group Information. 
As a result of some trial-and-errors, I found that the driver set the value that was left-shifted by 16-bit of  `ProtocolDataRequestSubValue3`.
For example, When I set `ProtocolDataRequestSubValue3` to `0x1111`, CDW11 became `0x11110000`; it seems that **it's not simply passed**.

I have added an implementation of getting Endurance Group Information to this tool (in `NVMeEnduranceGroup.c`) in the last commit.
I hope the code will help your understanding, and also resolving your problem.

Note: version of Windows 10 that I tested is Windows 10 Home Insider Preview 21286, the version of stornvme.sys is 10.0.21286.1000 (WinBuild 160101.0800)

**Comment by pomfei** [comment]
Hi @ken-yossy ,

Thank you for your great support.

I found that maybe my NVMe driver is old.

> Note: version of Windows 10 that I tested is Windows 10 Home Insider Preview 21286, the version of stornvme.sys is 10.0.21286.1000 (WinBuild 160101.0800)

My Windows 10 version is 2004 (19041.804) and the stornvme.sys is 10.0.19041.789. Maybe in this version the NVMe drive is not support the Endurance Group Information(09H).

I'll try the  Windows 10  Preview OS next,thanks for your support again :)

Regards,
Pomfei

**Comment by ken-yossy** [comment]
Hello @pomfei,

> My Windows 10 version is 2004 (19041.804) and the stornvme.sys is 10.0.19041.789. Maybe in this version the NVMe drive is not support the Endurance Group Information(09H).
> 
> I'll try the Windows 10 Preview OS next,thanks for your support again :)

Ok, I understand. Hope you go well with newer version of Windows.

Thank you,
Ken
