### ISSUE TITLE
get log page for vu  report error 1117 

### ISSUE THREAD

**Issue by hky7646480** [ken-yossy/nvmetool-win#17]
when i get log page (F0, it is a vendor specified ),   rerurn erro 1117 ,but when i get log page (DF ,it is also a vendor specified), it work ,  i am confused , ,both of them are vu  LID , why  F0 can not support, 

below is  my code 

CPP_API  ULONGLONG __cdecl AhciGetLogPageNVMe_F0(UINT  str)

{
	//str = 23;
	//int LID = 2;
	int LID = 0xf0;
	DWORD log_buffer[32] = { 0 };

	//UINT32 log_buffer[1024] = {0};
	BYTE SmartReadData[32] = { 0 };   //f0 length
	//log_buffer = &SmartReadData;
	TCHAR deviceName[MAX_PATH];

	//const TCHAR* SamsungTestPath = _T("\\\\.\\PhysicalDrive1");
	//DWORD log_length = 512;   //smart info 512 
	DWORD log_length = 32;

	PSTORAGE_PROPERTY_QUERY query;
	PSTORAGE_PROTOCOL_DATA_DESCRIPTOR protocolDataDescr;
	PSTORAGE_PROTOCOL_SPECIFIC_DATA protocolData;
	BOOL result;
	DWORD returnedLength;
	PVOID   buffer = NULL;

	DWORD bufferLength = FIELD_OFFSET(STORAGE_PROPERTY_QUERY, AdditionalParameters) + sizeof(STORAGE_PROTOCOL_SPECIFIC_DATA) + log_length;
	buffer = malloc(bufferLength);

	ZeroMemory(buffer, bufferLength);

	query = (PSTORAGE_PROPERTY_QUERY)buffer;
	protocolDataDescr = (PSTORAGE_PROTOCOL_DATA_DESCRIPTOR)buffer;
	protocolData = (PSTORAGE_PROTOCOL_SPECIFIC_DATA)query->AdditionalParameters;

	query->PropertyId = StorageDeviceProtocolSpecificProperty;
	query->QueryType = PropertyStandardQuery;

	protocolData->ProtocolType = ProtocolTypeNvme;
	protocolData->DataType = NVMeDataTypeLogPage;
	protocolData->ProtocolDataRequestValue = LID;
	//protocolData->ProtocolDataRequestSubValue = 1;
	protocolData->ProtocolDataRequestSubValue = 0;
	protocolData->ProtocolDataOffset = sizeof(STORAGE_PROTOCOL_SPECIFIC_DATA);
	//protocolData->ProtocolDataLength = sizeof(NVME_COMMAND_EFFECTS_LOG);
	protocolData->ProtocolDataLength = log_length;

	printf(("device_path  %X.\n"), ((UCHAR)deviceName));
	printf(("LID  %X.\n"), ((UCHAR)LID));
	m_hDisk = device();

	if (m_hDisk == INVALID_HANDLE_VALUE)    // cannot open the drive
	{
		printf("invalid device\n", ((UCHAR)("invalid device")));
		printf("open error %d\n", GetLastError());
	}

	result = DeviceIoControl(m_hDisk,
		IOCTL_STORAGE_QUERY_PROPERTY,
		buffer,
		bufferLength,
		buffer,
		bufferLength,
		&returnedLength,
		NULL
	);

	CloseHandle(m_hDisk);

	if (!result || (returnedLength == 0)) {
		printf(("AhciGetLogPageNVMe: failed. Error Code %d.\n"), GetLastError());
		goto exit;
	}
	//
	// Validate the returned data.
	//
	if ((protocolDataDescr->Version != sizeof(STORAGE_PROTOCOL_DATA_DESCRIPTOR)) ||
		(protocolDataDescr->Size != sizeof(STORAGE_PROTOCOL_DATA_DESCRIPTOR))) {
		printf(("AhciGetLogPageNVMe: - data descriptor header not valid.\n"));
		goto exit;
	}

	protocolData = &protocolDataDescr->ProtocolSpecificData;

	if ((protocolData->ProtocolDataOffset < sizeof(STORAGE_PROTOCOL_SPECIFIC_DATA)) ||
		(protocolData->ProtocolDataLength < log_length)) {
		//TraceInfo_DiskInfo(_T("AhciGetLogPageNVMe: ProtocolData Offset/Length not valid.\n"));
		goto exit;
	}
	memcpy((void*)log_buffer, (PCHAR)protocolData + protocolData->ProtocolDataOffset, log_length);

exit:
	PNVME_HEALTH_INFO_LOG smartInfo = (PNVME_HEALTH_INFO_LOG)((PCHAR)protocolData + protocolData->ProtocolDataOffset);
	switch (str)
	{
	
	case 23:
		tmp = (log_buffer[0]);
		printf("com 0 cnt \t%x\n", log_buffer[0]);
		printf("com 1 cnt \t%x\n", log_buffer[1]);
		printf("com 2 cnt \t%x\n", log_buffer[2]);
		printf("com 3 cnt \t%x\n", log_buffer[3]);
		printf("com 4 cnt \t%x\n", log_buffer[4]);
		printf("com 5 cnt \t%x\n", log_buffer[5]);
		printf("com 6 cnt \t%x\n", log_buffer[6]);
		break;
	case 24:
		tmp = (log_buffer[10]);
		printf("com cnt \t%x\n", tmp);
		printf("available \t%x\n", ((UCHAR)smartInfo->AvailableSpare));
		printf("temp1 \t%x\n", ((UCHAR)smartInfo->Temperature[1]));
		printf("temp2 \t%x\n", ((UCHAR)smartInfo->Temperature[2]));
		break;
	}
	//printf(("Temperature %d.\n"), ((ULONG)smartInfo->Temperature[1] << 8 | smartInfo->Temperature[0]) - 273);
	//printf(("AvailableSpareThreshold %X.\n"), ((UCHAR)smartInfo->AvailableSpareThreshold));
	//printf(("AvailableSpare %X.\n"), ((UCHAR)smartInfo->AvailableSpare));
	//printf(("PercentageUsed %X.\n"), ((UCHAR)smartInfo->PercentageUsed));
	//printf(("WarningCompositeTemperatureTime %X.\n"), ((UCHAR)smartInfo->WarningCompositeTemperatureTime));
	//printf(("CriticalCompositeTemperatureTime %X.\n"), ((UCHAR)smartInfo->CriticalCompositeTemperatureTime));
	//printf("DataUnitRead\t%x\n", data_get(smartInfo->DataUnitRead, 16));
	//printf("DataUnitWritten\t%x\n", data_get(smartInfo->DataUnitWritten, 16));
	//printf("HostReadCommands\t%x\n", data_get(smartInfo->HostReadCommands, 16));
	//printf("HostWrittenCommands\t%x\n", data_get(smartInfo->HostWrittenCommands, 16));
	//printf("ControllerBusyTime\t%x\n", data_get(smartInfo->ControllerBusyTime, 16));
	//printf("PowerCycle\t%x\n", data_get(smartInfo->PowerCycle, 16));
	//printf("PowerOnHours\t%x\n", data_get(smartInfo->PowerOnHours, 16));
	//printf("UnsafeShutdowns\t%x\n", data_get(smartInfo->UnsafeShutdowns, 16));
	//printf("MediaErrors\t%x\n", data_get(smartInfo->MediaErrors, 16));
	//printf("ErrorInfoLogEntryCount\t%x\n", data_get(smartInfo->ErrorInfoLogEntryCount, 16));

	//cout << typeid(smartInfo->AvailableSpare).name() << endl;
	printf(("type of output  .\n"), tmp);
	free(buffer);

	return tmp;//   very good , based on the help from jinlei ,success 
}

**Comment by ken-yossy** [comment]
Hi,

Your situation is as follows... right?  "Both LID 0xF0 and 0xDF are vendor specific, but results are different (0xF0: failed, 0xDF: succeeded)"

Well...my suggestion is to issue `Get Log Page` command as "vendor specific command" as described in [this page](https://docs.microsoft.com/en-us/windows/win32/fileio/working-with-nvme-devices#example-sending-a-vendor-specific-command).

Followings are the reasons for my suggestion:
1. Even if you send well-known (defined in NVMe spec) command (`Get Log Page` command), the command with vendor specific LID might be recognized as an unknown command by Windows. So the behavior of Windows might be undefined.
2. As `Get Log Page` command is well-known command, Windows probably have specific processes for handling it. It could be problem for sending vendor specific LIDs. On the other hand, processing vendor specific commands should be "pass-through". So, for passing vendor specific LID to devices properly, I think using mechanism of "vendor specific command" may be more suitable. 

Note: it has not confirmed working for your situation...

Regards,
Ken
