### ISSUE TITLE
ken-yossy, can you give me your email, i want to contact with you, thx.

### ISSUE THREAD

**Issue by adeamlee** [ken-yossy/nvmetool-win#28]
Hi ken-yossy;
     I am an engineer in china who develop nvme test python lib with boost c++ lib;
     can you give me your email or other information, i want to contact with you, thx.

**Comment by ken-yossy** [comment]
Hi,

You can post any questions with handling NVMe drive (ex. about NVMe spec) into this issue tracker!
But I'm not sure that I could tell you what you need...

Thank you,
Ken
