### ISSUE TITLE
C++ support

### ISSUE THREAD

**Issue by tim-oleksii** [ken-yossy/nvmetool-win#7]
Is there any reason why this project considered as C++ one? I see `#include <iostream>` or `#include <string>` but they don't seem to be used.

**Comment by ken-yossy** [comment]
Hi Alexey,

Thank you for your comment and reminding me of that.

> Is there any reason why this project considered as C++ one? I see `#include <iostream>` or `#include <string>` but they don't seem to be used.

No, because I've thought it as low priority, I have simply left it in that state so far.
I will to make it right.

Ken

**Comment by ken-yossy** [comment]
I plan to put this issue ahead of #6.

**Comment by ken-yossy** [comment]
With the recent sequence of commits, this project has been recognized as pure C project.

@tim-oleksii 
If you are still watching this ticket, do you mind closing it?
Even if you do not close, I will close it after a week.

Again, thank you for your comments.

Ken
